// Report-generation contract. Question items measure definition-aligned
// behaviors only; subject applications and coach actions are never item stems.
export const PREFERENCE_MODULES = Object.freeze([
  { id: "information_location", preference: "V", label: "找到重点", definition: "借助颜色、符号、版面位置和重点标记快速找到当前任务的关键信息。", typicalBehaviors: ["标题、重点和条件标记能帮助找到关键信息", "位置或符号线索能帮助回想信息"], subjectApplications: ["在材料、题干或笔记中定位条件、证据和关键关系"], coachActions: ["引导学生标出有限的关键信息，再遮盖材料进行回忆核对"] },
  { id: "graphic_representation", preference: "V", label: "图形理解", definition: "材料以示意图、关系图、图表或流程图呈现，帮助学习者从图形线索开始理解内容。", typicalBehaviors: ["材料配有示意图、关系图或流程图", "步骤说明同时呈现图解或流程示意"], subjectApplications: ["在概念关系、过程链或解题路径中提供可参照的图形"], coachActions: ["引导学生自己建图，并用空白图或口头解释检查图中关系"] },
  { id: "relationship_organization", preference: "V", label: "理清关系", definition: "通过流程、层级、因果和位置关系组织信息，形成整体结构。", typicalBehaviors: ["先后和层级关系能帮助看清整体", "步骤之间的连接清楚时更容易理解过程"], subjectApplications: ["组织章节结构、过程链、条件与结论之间的关系"], coachActions: ["让学生重新排列关系并说明每一部分与整体的连接"] },
  { id: "difference_identification", preference: "V", label: "比较差异", definition: "通过并排对照条件、做法和结果，识别相似信息之间的关键差异。", typicalBehaviors: ["并排比较能帮助发现相似内容的差异", "变化条件被标出时更容易辨认结果差别"], subjectApplications: ["比较题型变式、概念边界、错误做法与正确做法"], coachActions: ["用对照任务追问差异出现的位置，并要求迁移到新例子"] },
  { id: "explanation_comprehension", preference: "A", label: "听讲解", definition: "通过有顺序的口头讲解理解概念、步骤和来龙去脉。", typicalBehaviors: ["顺序清楚的解释能帮助进入理解", "讲解能帮助抓住因果和依据"], subjectApplications: ["用口头讲解建立概念、过程和解题依据的初步理解"], coachActions: ["讲解后要求学生脱离讲解复述依据并独立完成一小步"] },
  { id: "sound_cues", preference: "A", label: "声音线索", definition: "借助朗读、节奏、关键词声音和提示语形成可调用的记忆线索。", typicalBehaviors: ["朗读和节奏能帮助留下关键词线索", "提示语能帮助唤回内容"], subjectApplications: ["保持术语、步骤提示、公式条件和语言表达线索"], coachActions: ["保留少量关键词声音线索，并安排不看材料的恢复任务"] },
  { id: "language_expression", preference: "A", label: "说出思路", definition: "通过用自己的话说出理解、理由或过程，组织并检查当前认识。", typicalBehaviors: ["用自己的话复述时思路更容易清楚", "口头说明理由能帮助检查理解"], subjectApplications: ["解释概念、解题依据、材料证据和订正原因"], coachActions: ["让学生先说完整理由，再留下书面或独立作答证据"] },
  { id: "question_answer_interaction", preference: "A", label: "一问一答", definition: "围绕具体内容，通过一问一答或简短追问呈现解释和依据。", typicalBehaviors: ["根据回答继续追问更容易理清关系", "简短问答能帮助弄清不明白的地方"], subjectApplications: ["在概念辨析、解题依据和反馈订正中通过问答补充说明"], coachActions: ["用具体追问定位模糊处，要求学生给出依据而非停留在聊天"] },
  { id: "text_comprehension", preference: "R", label: "读懂文字", definition: "通过文字定义、条件、说明和例子准确进入内容理解。", typicalBehaviors: ["文字定义和使用条件能帮助进入理解", "书面说明能帮助确认细节"], subjectApplications: ["理解概念、题目要求、材料信息和规范表达"], coachActions: ["引导学生圈出定义与条件，并离开原文回答问题"] },
  { id: "structure_organization", preference: "R", label: "结构整理", definition: "通过标题、分点、分类和段落把零散信息整理为可复习的书面结构。", typicalBehaviors: ["标题和分组能帮助整理零散内容", "用小标题分开要求、做法和错因时更容易理清问题"], subjectApplications: ["整理课堂重点、错因、方法和材料论证结构"], coachActions: ["将整理结果改写为问题清单，安排闭卷恢复而非只美化笔记"] },
  { id: "written_expression", preference: "R", label: "写出思路", definition: "通过写出要点、步骤、依据或自己的话，把理解转成可检查的书面输出。", typicalBehaviors: ["写下自己的解释能帮助理清思路", "书面步骤和依据能帮助检查遗漏"], subjectApplications: ["完成解题过程、材料分析、答案表达和错因说明"], coachActions: ["按准确、完整和依据三个标准核对书面输出"] },
  { id: "rule_presentation", preference: "R", label: "提取规则", definition: "材料把条件、步骤、注意事项或规则分条写清，供学习者参照。", typicalBehaviors: ["说明把条件、步骤和注意事项分条写清", "题目要求或作答规则把注意点清楚写出"], subjectApplications: ["以条目形式呈现题目条件、术语边界、答题规范和操作要求"], coachActions: ["要求学生先提取规则再完成任务，并用遗漏检查验证清单"] },
  { id: "case_entry", preference: "K", label: "例子开始", definition: "从代表性例题、事例或示范进入抽象内容，建立原理与具体情境的连接。", typicalBehaviors: ["具体示例能帮助进入抽象内容", "案例能帮助理解规则怎样使用"], subjectApplications: ["用例题、实验现象、文本事例或真实问题启动理解"], coachActions: ["追问案例与原理的对应，再换一个例子验证"] },
  { id: "hands_on_trial", preference: "K", label: "动手试试", definition: "通过亲自完成一个可立即尝试的小步骤，形成对工具、方法或过程的理解。", typicalBehaviors: ["亲自试一个小步骤更容易找到开始位置", "再试一个关键步骤更容易想起它的作用"], subjectApplications: ["尝试工具操作、解题步骤、实验分析或表达任务"], coachActions: ["限定小任务范围，要求尝试后说清做法并独立重做"] },
  { id: "process_rehearsal", preference: "K", label: "过程演练", definition: "通过脑中或实际按顺序演练过程、角色或近真实任务，理解步骤和选择依据。", typicalBehaviors: ["按顺序演练能帮助理解过程", "完整走一遍更容易记清步骤怎样衔接"], subjectApplications: ["演练实验、解题流程、语言使用和材料处理过程"], coachActions: ["让学生还原过程并解释每一步选择的依据"] },
  { id: "contextual_presentation", preference: "K", label: "情境应用", definition: "材料把正确做法或操作说明放在具体使用情境中展示。", typicalBehaviors: ["订正材料在具体情境中演示正确做法", "操作说明放在实际使用情境中展示"], subjectApplications: ["在变式题、新材料和真实使用情境中展示当前方法"], coachActions: ["提供条件略变的新任务，依据独立结果反馈迁移是否成立"] }
]);
